apiVersion: v1
kind: PersistentVolume
metadata:
  name: {{ include "vpn.fullname" . }}
  labels:
    app.kubernetes.io/name: {{ include "vpn.name" . }}
    helm.sh/chart: {{ include "vpn.chart" . }}
    app.kubernetes.io/instance: {{ .Release.Name }}
    app.kubernetes.io/managed-by: {{ .Release.Service }}
spec:
  capacity:
    storage: 5Gi
  accessModes:
  - ReadWriteOnce
  persistentVolumeReclaimPolicy: Retain
  hostPath:
    path: /lib/modules
